src/Redis.mvc/Models/ErrorViewModel.cs
using System;

namespace Redis.mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Redis.mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Redis.mvc.Models;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Redis.mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConnectionMultiplexer _redis;
        private readonly IDistributedCache _distributedCashe;
        private readonly IDatabase _db;

        public HomeController(ILogger<HomeController> logger, 
            IConnectionMultiplexer redis,
            IDistributedCache distributedCashe)
        {
            _logger = logger;
            _redis = redis;
            _distributedCashe = distributedCashe;
            _db = _redis.GetDatabase();
        }

        public IActionResult Index()
        {
            //Get, GetAsync: Accepts a string key and retrieves a cached item as a byte[] array if found in the cache.
            //Set, SetAsync: Adds an item(as byte[] array) to the cache using a string key.
            //Refresh, RefreshAsync: Refreshes an item in the cache based on its key, resetting its sliding expiration timeout(if any).
            //Remove, RemoveAsync: Removes a cache item based on its string key.
            var value = _distributedCashe.Get("name-key");
            if (value == null)
            {
                var obj = new Dictionary<string, string>
                {
                    ["FirstName"] = "Nick",
                    ["LastName"] = "Carter",
                };
                var str = JsonConvert.SerializeObject(obj);
                byte[] encoded = Encoding.UTF8.GetBytes(str);
                var options = new DistributedCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromSeconds(30));
                _distributedCashe.Set("name-key", encoded, options);
                return View(obj);
            }
            else
            {
                var str = Encoding.UTF8.GetString(value);
                var obj = JsonConvert.DeserializeObject<Dictionary<string,string>>(str);
                return View(obj);
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Redis.mvc/ViewComponents/CounterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Redis.mvc.ViewComponents
{
    public class CounterViewComponent:ViewComponent
    {
        private readonly IDatabase _db;
        public CounterViewComponent(IConnectionMultiplexer redis)
        {
            _db = redis.GetDatabase();
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var controller = RouteData.Values["controller"] as string;
            var action = RouteData.Values["action"] as string;
            if (!string.IsNullOrWhiteSpace(controller) && !string.IsNullOrWhiteSpace(action))
            {
                var pageId = $"{controller}-{action}";
                await _db.StringIncrementAsync(pageId);
                var count =await _db.StringGetAsync(pageId);
                return View("Default", pageId + ": " + count);
            }
            throw new Exception("Cannot get pageId");
        }
    }
}

src/Redis.mvc/Views/Home/Index.cshtml
@model Dictionary<string, string>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome:@Model</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @foreach (var item in Model)
    {
        <h3>
            @item.Key:@item.Value
        </h3>
    }
</div>

src/Redis.mvc/Views/Shared/Components/Counter/Default.cshtml
@model string

<h4>
    @Model
</h4>

src/Redis.mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Redis.mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Redis.mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div>
            @await Component.InvokeAsync("Counter");
        </div>
        <div class="container">
            &copy; 2021 - Redis.mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>